name: intelligent_expense_claim_app
description: "Intelligent Expense Claim (IEC) application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Core utilities
  uuid: ^4.5.1
  intl: ^0.19.0

  # Camera & media
  image_picker: ^1.0.8
  path_provider: ^2.1.4

  # Location & permissions
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
